[package]
name = "pata-cli"
version = "0.5.0"
edition = "2021"

[dependencies]
asili-diagnostics = { path = "../../core/diagnostics" }
asili-lexer = { path = "../../core/lexer" }
asili-parser = { path = "../../core/parser" }
asili-evaluator = { path = "../../core/evaluator" }
pata-package = { path = "../package" }
pata-lsp = { path = "../lsp" }
sha2 = "0.11.0"
pulldown-cmark = "0.13"
anyhow = "1.0"
serde_json = "1"
rayon = "1.7"
